CREATE OR REPLACE PACKAGE NOMBRE_PACKAGE IS
    FUNCTION RETORNAR_SUMA(NUMNERO1 NUMBER, NUMNERO2 NUMBER) RETURN NUMBER;
    PROCEDURE ACTUALIZAR_FECHA(FECHA DATE);
END NOMBRE_PACKAGE;

CREATE OR REPLACE PACKAGE BODY NOMBRE_PACKAGE IS
    --///
    FUNCTION RETORNAR_SUMA(NUMNERO1 NUMBER, NUMNERO2 NUMBER) RETURN NUMBER IS
    SUMA NUMBER := 0;
    BEGIN
        FOR i IN NUMNERO1..NUMNERO2 LOOP
        SUMA := i + SUMA;
        DBMS_OUTPUT.PUT_LINE(SUMA);
        END LOOP;
        RETURN SUMA;
    END RETORNAR_SUMA;
    --//
    PROCEDURE ACTUALIZAR_FECHA(FECHA DATE) IS
    BEGIN
    UPDATE estudiante
    SET fecha_actualizacion = FECHA;
    END ACTUALIZAR_FECHA;
    --///
END NOMBRE_PACKAGE;

SELECT nombre_package.retornar_suma(1, 1000) FROM DUAL;--//DUAL TABLA FICTICIA//FUNCIONES  
CALL nombre_package.actualizar_fecha(SYSDATE/'08/08/2008');--// PROCEDIMIENTOS

FUNCTION TOTAL_ESTUDIANTES(P_ID NUMBER) RETURN NUMBER IS

    TOTAL NUMBER;
BEGIN
    SELECT COUNT(ID) INTO TOTAL 
      FROM ESTUDIANTE 
     WHERE SEXO = 'M';

    RETURN TOTAL;

END TOTAL_ESTUDIANTES;

/*Crear una function que retorne el total de estudiantes hombres o mujeres segun se indique*/
--COUNT([PARAMETER]) esto devuelve el total de filas segun la consulta
/*Crear un procedimiento que actualice la fecha de un estudiante en especifico*/
/*ESTOS DOS TIENEN QUE IR EN UN PAQUETE LLAMADO METODOS ESTUDIANTES*/

create or replace PACKAGE METODOS_ESTUDIANTES IS
    FUNCTION TOTAL_ESTUDIANTES(P_SEXO VARCHAR2) RETURN NUMBER;
    PROCEDURE ACTUALIZACION_FECHA(P_ID NUMBER, P_FECHA DATE);
END METODOS_ESTUDIANTES;

create or replace PACKAGE BODY METODOS_ESTUDIANTES IS
 --///
    FUNCTION TOTAL_ESTUDIANTES(P_SEXO VARCHAR2) RETURN NUMBER IS 
        TOTAL NUMBER;
    BEGIN
        SELECT COUNT(ID) INTO TOTAL
            FROM ESTUDIANTE
            WHERE SEXO = P_SEXO;
    RETURN TOTAL;
    END TOTAL_ESTUDIANTES;
--//
    PROCEDURE ACTUALIZACION_FECHA(P_ID NUMBER, P_FECHA DATE) IS
    BEGIN  
    UPDATE estudiante
    SET FECHA_ACTUALIZACION = P_FECHA
    WHERE ID = P_ID;
    END ACTUALIZACION_FECHA;
--//
 END METODOS_ESTUDIANTES;
SELECT
  FROM
 WHERE
 GROUP BY
 ORDER BY
